import ItemCard from "./ItemCard";
function MenuGrid(){
const foods = [
  {
    id: 1,
    img: "/Pic/Butter_Chicken.jpg",
    item: "Popular",
    name: "Butter Chicken",
    about: "Rich tomato and cream curry with tender chicken pieces.",
    price: 299,
  },
  {
    id: 2,
    img: "",
    item: "Spicy",
    name: "Chicken Biryani",
    about: "Aromatic basmati rice cooked with flavorful spices and chicken.",
    price: 249,
  },
  {
    id: 3,
    img: "./public/pic/Butter_Chicken",
    item: "Hype",
    name: "Margherita Pizza",
    about: "Classic pizza topped with fresh mozzarella and basil.",
    price: 349,
  },
  {
    id: 4,
    img: "./public/pic/Butter_Chicken",
    item: "Popular",
    name: "Cheese Burger",
    about: "Juicy grilled patty with melted cheese and fresh veggies.",
    price: 199,
  },
  {
    id: 5,
    img: "./public/pic/Butter_Chicken",
    item: "Spicy",
    name: "Paneer Tikka",
    about: "Smoky grilled paneer cubes marinated in Indian spices.",
    price: 229,
  },
  {
    id: 6,
    img: "",
    item: "Hype",
    name: "Ramen Bowl",
    about: "Japanese noodle soup with rich broth and toppings.",
    price: 329,
  },
  {
    id: 7,
    img: "./public/pic/Butter_Chicken",
    item: "Popular",
    name: "Caesar Salad",
    about: "Fresh lettuce tossed with creamy dressing and croutons.",
    price: 179,
  },
  {
    id: 8,
    img: "https://source.unsplash.com/600x400/?chicken-wings",
    item: "Spicy",
    name: "Hot Wings",
    about: "Crispy chicken wings coated in fiery hot sauce.",
    price: 259,
  },
  {
    id: 9,
    img: "https://source.unsplash.com/600x400/?fries",
    item: "Hype",
    name: "Loaded Fries",
    about: "Crispy fries topped with cheese, sauces, and seasonings.",
    price: 149,
  },
  {
    id: 10,
    img: "https://source.unsplash.com/600x400/?lava-cake",
    item: "Popular",
    name: "Chocolate Lava Cake",
    about: "Warm chocolate cake with a gooey molten center.",
    price: 189,
  },
  {
    id: 11,
    img: "https://source.unsplash.com/600x400/?tandoori-chicken",
    item: "Spicy",
    name: "Tandoori Chicken",
    about: "Chicken marinated in yogurt and spices, grilled to perfection.",
    price: 349,
  },
  {
    id: 12,
    img: "https://source.unsplash.com/600x400/?masala-dosa",
    item: "Popular",
    name: "Masala Dosa",
    about: "Crispy rice crepe filled with flavorful potato masala.",
    price: 129,
  },
  {
    id: 13,
    img: "https://source.unsplash.com/600x400/?paneer-butter-masala",
    item: "Popular",
    name: "Paneer Butter Masala",
    about: "Soft paneer cubes in a rich buttery tomato gravy.",
    price: 279,
  },
  {
    id: 14,
    img: "https://source.unsplash.com/600x400/?noodles",
    item: "Hype",
    name: "Hakka Noodles",
    about: "Stir-fried noodles tossed with vegetables and sauces.",
    price: 199,
  },
  {
    id: 15,
    img: "https://source.unsplash.com/600x400/?chicken-tikka",
    item: "Spicy",
    name: "Chicken Tikka",
    about: "Juicy boneless chicken pieces grilled with Indian spices.",
    price: 299,
  },
  {
    id: 16,
    img: "https://source.unsplash.com/600x400/?fried-rice",
    item: "Popular",
    name: "Veg Fried Rice",
    about: "Flavorful rice stir-fried with fresh vegetables.",
    price: 179,
  },
  {
    id: 17,
    img: "https://source.unsplash.com/600x400/?momos",
    item: "Hype",
    name: "Chicken Momos",
    about: "Steamed dumplings stuffed with juicy chicken filling.",
    price: 149,
  },
  {
    id: 18,
    img: "https://source.unsplash.com/600x400/?fish-curry",
    item: "Popular",
    name: "Fish Curry",
    about: "Fresh fish cooked in a tangy and spicy curry.",
    price: 329,
  },
  {
    id: 19,
    img: "https://source.unsplash.com/600x400/?chole-bhature",
    item: "Popular",
    name: "Chole Bhature",
    about: "Spiced chickpeas served with fluffy fried bread.",
    price: 169,
  },
  {
    id: 20,
    img: "https://source.unsplash.com/600x400/?schezwan-rice",
    item: "Spicy",
    name: "Schezwan Rice",
    about: "Rice tossed in fiery Schezwan sauce and vegetables.",
    price: 219,
  },
  {
    id: 21,
    img: "https://source.unsplash.com/600x400/?pasta",
    item: "Hype",
    name: "White Sauce Pasta",
    about: "Creamy pasta loaded with herbs and vegetables.",
    price: 249,
  },
  {
    id: 22,
    img: "https://source.unsplash.com/600x400/?kadai-paneer",
    item: "Popular",
    name: "Kadai Paneer",
    about: "Paneer cooked with capsicum and aromatic spices.",
    price: 289,
  },
  {
    id: 23,
    img: "https://source.unsplash.com/600x400/?spring-rolls",
    item: "Hype",
    name: "Spring Rolls",
    about: "Crispy rolls stuffed with seasoned vegetables.",
    price: 139,
  },
  {
    id: 24,
    img: "https://source.unsplash.com/600x400/?prawns",
    item: "Spicy",
    name: "Prawns Fry",
    about: "Crispy prawns coated with spicy masala seasoning.",
    price: 399,
  },
  {
    id: 25,
    img: "https://source.unsplash.com/600x400/?hyderabadi-biryani",
    item: "Popular",
    name: "Hyderabadi Biryani",
    about: "Authentic dum-cooked biryani packed with rich flavors.",
    price: 329,
  },
  {
    id: 26,
    img: "https://source.unsplash.com/600x400/?sandwich",
    item: "Hype",
    name: "Club Sandwich",
    about: "Triple-layer sandwich filled with veggies and chicken.",
    price: 189,
  },
  {
    id: 27,
    img: "https://source.unsplash.com/600x400/?chilli-paneer",
    item: "Spicy",
    name: "Chilli Paneer",
    about: "Paneer cubes tossed in a spicy Indo-Chinese sauce.",
    price: 239,
  },
  {
    id: 28,
    img: "https://source.unsplash.com/600x400/?manchurian",
    item: "Popular",
    name: "Veg Manchurian",
    about: "Vegetable balls cooked in a savory Chinese-style gravy.",
    price: 209,
  },
  {
    id: 29,
    img: "https://source.unsplash.com/600x400/?brownie",
    item: "Hype",
    name: "Brownie Sizzler",
    about: "Hot chocolate brownie served with ice cream.",
    price: 229,
  },
  {
    id: 30,
    img: "https://source.unsplash.com/600x400/?red-velvet-cake",
    item: "Popular",
    name: "Red Velvet Cake",
    about: "Soft and moist cake layered with cream cheese frosting.",
    price: 199,
  },
];

    return(
        
        <div className="px-4 sm:px-6 md:px-10 my-10 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 ">
        {
        foods.map(function(ele) {
            return(
                <ItemCard key={ele.id} img={ele.img} item={ele.item} name={ele.name} about={ele.about} price={ele.price}/>
              
            ) 
        })
    }
        </div>
    )
}
export default MenuGrid;
